//! Subsumption poset — the shared model behind time, geography and ontology hierarchies.
//!
//! A *relationship hierarchy* is a labeled partial order generated by a **covering
//! relation**. We store the covering relation as directed edges `child -> parent`: an edge
//! `(c, p)` means *c is directly subsumed by p* (`c ⊑ p`). The reflexive-transitive closure
//! of that relation is the subsumption order.
//!
//! Conventions used throughout the hierarchy module:
//!
//! - `subsumes(x, y)` == `x ⊑ y` == *y is an ancestor of x* == *x is a descendant of y*.
//! - The relation is reflexive: `subsumes(x, x)` is always true.
//! - The covering relation must be acyclic. A cycle is a data bug, not something to
//!   condense away: silently collapsing an SCC would make every roll-up over it wrong.
//!
//! Internally the poset works in **dense indices** (`u32`) rather than [`NodeId`]s. Graph
//! node ids are sparse `u64`s; the hierarchy structures (interval arrays, Fenwick trees,
//! chain tables) all want contiguous 0..n addressing. [`Poset::idx`] and [`Poset::node_at`]
//! translate at the boundary.

use std::collections::HashMap;

use crate::graph::types::{EdgeType, NodeId};
use crate::graph::GraphStore;

/// Errors raised while building or using a hierarchy.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum HierarchyError {
    /// The covering relation contains a directed cycle. Carries how many nodes could be
    /// topologically ordered before the sort stalled, which is a useful size hint when
    /// debugging a bad ontology import.
    NotAcyclic { ordered: usize, total: usize },
    /// The poset is a DAG whose chain width exceeds the cap; a 2-hop index is the right
    /// substrate there. This is a *decline*, not a failure — see ADR-035.
    WidthTooHigh {
        width: usize,
        cap: usize,
        nodes: usize,
    },
    /// A NestedSet encoding was forced on a poset that is not a tree.
    NotATree,
    /// The named node is not part of this hierarchy.
    UnknownNode(NodeId),
    /// The requested index name does not exist.
    NoSuchIndex(String),
    /// An index with this name already exists.
    DuplicateIndex(String),
    /// The index is stale with respect to the graph and stale reads were not requested.
    Stale(String),
}

impl std::fmt::Display for HierarchyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            HierarchyError::NotAcyclic { ordered, total } => write!(
                f,
                "covering relation has a cycle: only {ordered}/{total} nodes could be ordered"
            ),
            HierarchyError::WidthTooHigh { width, cap, nodes } => write!(
                f,
                "hierarchy declined: chain width {width} exceeds cap {cap} (~8·sqrt({nodes})); \
                 chain space is O(n·width) — use a 2-hop index for this poset"
            ),
            HierarchyError::NotATree => write!(f, "nested-set encoding requires a tree poset"),
            HierarchyError::UnknownNode(id) => write!(f, "node {id} is not in this hierarchy"),
            HierarchyError::NoSuchIndex(n) => write!(f, "no hierarchy index named '{n}'"),
            HierarchyError::DuplicateIndex(n) => write!(f, "hierarchy index '{n}' already exists"),
            HierarchyError::Stale(n) => write!(
                f,
                "hierarchy index '{n}' is stale; REBUILD it or opt into stale reads"
            ),
        }
    }
}

impl std::error::Error for HierarchyError {}

/// Result alias for hierarchy operations.
pub type HierarchyResult<T> = Result<T, HierarchyError>;

/// A subsumption poset over a set of graph nodes.
#[derive(Debug, Clone)]
pub struct Poset {
    /// Dense index -> graph node id.
    nodes: Vec<NodeId>,
    /// Graph node id -> dense index.
    index_of: HashMap<NodeId, u32>,
    /// `parents[i]` = dense indices directly subsuming `i`.
    parents: Vec<Vec<u32>>,
    /// `children[i]` = dense indices directly subsumed by `i`.
    children: Vec<Vec<u32>>,
    /// Topological order with every child before its parents.
    topo_up: Vec<u32>,
    /// Number of distinct covering edges.
    edge_count: usize,
}

impl Poset {
    /// Build a poset from `child -> parent` edges.
    ///
    /// `extra_nodes` lets a caller include isolated nodes that participate in the
    /// hierarchy conceptually but have no covering edge (e.g. a taxonomy root imported
    /// without a parent link). Duplicate edges are collapsed; self-loops are a cycle and
    /// are rejected.
    pub fn from_edges<I, N>(edges: I, extra_nodes: N) -> HierarchyResult<Self>
    where
        I: IntoIterator<Item = (NodeId, NodeId)>,
        N: IntoIterator<Item = NodeId>,
    {
        let mut nodes: Vec<NodeId> = Vec::new();
        let mut index_of: HashMap<NodeId, u32> = HashMap::new();
        let intern = |id: NodeId, nodes: &mut Vec<NodeId>, map: &mut HashMap<NodeId, u32>| -> u32 {
            *map.entry(id).or_insert_with(|| {
                nodes.push(id);
                (nodes.len() - 1) as u32
            })
        };

        for id in extra_nodes {
            intern(id, &mut nodes, &mut index_of);
        }

        let mut raw: Vec<(u32, u32)> = Vec::new();
        for (child, parent) in edges {
            let c = intern(child, &mut nodes, &mut index_of);
            let p = intern(parent, &mut nodes, &mut index_of);
            raw.push((c, p));
        }

        let n = nodes.len();
        let mut parents: Vec<Vec<u32>> = vec![Vec::new(); n];
        let mut children: Vec<Vec<u32>> = vec![Vec::new(); n];
        let mut seen: std::collections::HashSet<(u32, u32)> = std::collections::HashSet::new();
        let mut edge_count = 0usize;
        for (c, p) in raw {
            if !seen.insert((c, p)) {
                continue;
            }
            parents[c as usize].push(p);
            children[p as usize].push(c);
            edge_count += 1;
        }

        let topo_up = Self::topo_sort_up(&parents, n)?;
        Ok(Poset {
            nodes,
            index_of,
            parents,
            children,
            topo_up,
            edge_count,
        })
    }

    /// Build a poset from every edge in `store` whose type is one of `edge_types`.
    ///
    /// Edges are read in their stored direction: `child -[:IS_A]-> parent`. Callers that
    /// model the relation the other way round (`parent -[:HAS_CHILD]-> child`) should pass
    /// `reverse = true`.
    pub fn from_store(
        store: &GraphStore,
        edge_types: &[EdgeType],
        reverse: bool,
    ) -> HierarchyResult<Self> {
        let mut edges: Vec<(NodeId, NodeId)> = Vec::new();
        for et in edge_types {
            for edge in store.get_edges_by_type(et) {
                if reverse {
                    edges.push((edge.target, edge.source));
                } else {
                    edges.push((edge.source, edge.target));
                }
            }
        }
        Poset::from_edges(edges, std::iter::empty())
    }

    /// Kahn topological sort on `child -> parent` edges, producing children before parents.
    fn topo_sort_up(parents: &[Vec<u32>], n: usize) -> HierarchyResult<Vec<u32>> {
        // in-degree counted on the *parent* side: how many children point at me.
        let mut indeg = vec![0u32; n];
        for plist in parents.iter() {
            for &p in plist {
                indeg[p as usize] += 1;
            }
        }
        let mut queue: std::collections::VecDeque<u32> =
            (0..n as u32).filter(|&i| indeg[i as usize] == 0).collect();
        let mut order = Vec::with_capacity(n);
        while let Some(u) = queue.pop_front() {
            order.push(u);
            for &p in &parents[u as usize] {
                indeg[p as usize] -= 1;
                if indeg[p as usize] == 0 {
                    queue.push_back(p);
                }
            }
        }
        if order.len() != n {
            return Err(HierarchyError::NotAcyclic {
                ordered: order.len(),
                total: n,
            });
        }
        Ok(order)
    }

    /// Number of nodes.
    pub fn n(&self) -> usize {
        self.nodes.len()
    }

    /// Number of distinct covering edges.
    pub fn m(&self) -> usize {
        self.edge_count
    }

    /// Dense index for a graph node, if it participates in the hierarchy.
    pub fn idx(&self, id: NodeId) -> Option<u32> {
        self.index_of.get(&id).copied()
    }

    /// Graph node id for a dense index.
    pub fn node_at(&self, i: u32) -> NodeId {
        self.nodes[i as usize]
    }

    /// All node ids, in dense-index order.
    pub fn node_ids(&self) -> &[NodeId] {
        &self.nodes
    }

    /// Direct parents (things that directly subsume `i`).
    pub fn parents(&self, i: u32) -> &[u32] {
        &self.parents[i as usize]
    }

    /// Direct children (things `i` directly subsumes).
    pub fn children(&self, i: u32) -> &[u32] {
        &self.children[i as usize]
    }

    /// Maximal elements — the tops of the hierarchy.
    pub fn roots(&self) -> Vec<u32> {
        (0..self.n() as u32)
            .filter(|&i| self.parents[i as usize].is_empty())
            .collect()
    }

    /// Minimal elements.
    pub fn leaves(&self) -> Vec<u32> {
        (0..self.n() as u32)
            .filter(|&i| self.children[i as usize].is_empty())
            .collect()
    }

    /// Topological order, every child before its parents.
    pub fn topo_up(&self) -> &[u32] {
        &self.topo_up
    }

    /// Topological order, every parent before its children.
    pub fn topo_down(&self) -> Vec<u32> {
        self.topo_up.iter().rev().copied().collect()
    }

    /// The structural probe's first question: does every node have at most one parent?
    ///
    /// A tree (or forest) admits the nested-set encoding, which is both smaller and
    /// faster than chain decomposition, so this test is worth its single pass.
    pub fn is_tree(&self) -> bool {
        self.parents.iter().all(|p| p.len() <= 1)
    }

    /// Maximum depth from any root, for diagnostics and benchmark stratification.
    pub fn max_depth(&self) -> usize {
        let mut depth = vec![0usize; self.n()];
        let mut max = 0usize;
        for &v in self.topo_down().iter() {
            let d = self.parents[v as usize]
                .iter()
                .map(|&p| depth[p as usize] + 1)
                .max()
                .unwrap_or(0);
            depth[v as usize] = d;
            max = max.max(d);
        }
        max
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn nid(i: u64) -> NodeId {
        NodeId(i)
    }

    /// `1,2 ⊑ 0` — a two-level tree.
    fn small_tree() -> Poset {
        Poset::from_edges(vec![(nid(1), nid(0)), (nid(2), nid(0))], std::iter::empty()).unwrap()
    }

    #[test]
    fn builds_tree_and_reports_shape() {
        let p = small_tree();
        assert_eq!(p.n(), 3);
        assert_eq!(p.m(), 2);
        assert!(p.is_tree());
        assert_eq!(p.roots().len(), 1);
        assert_eq!(p.leaves().len(), 2);
        assert_eq!(p.max_depth(), 1);
    }

    #[test]
    fn duplicate_edges_are_collapsed() {
        let p = Poset::from_edges(
            vec![(nid(1), nid(0)), (nid(1), nid(0)), (nid(1), nid(0))],
            std::iter::empty(),
        )
        .unwrap();
        assert_eq!(p.m(), 1);
        assert_eq!(p.parents(p.idx(nid(1)).unwrap()).len(), 1);
    }

    #[test]
    fn extra_nodes_join_the_poset_without_edges() {
        let p = Poset::from_edges(vec![(nid(1), nid(0))], vec![nid(9)]).unwrap();
        assert_eq!(p.n(), 3);
        assert!(p.idx(nid(9)).is_some());
        // an isolated node is both a root and a leaf
        assert_eq!(p.roots().len(), 2);
    }

    #[test]
    fn diamond_is_not_a_tree() {
        // 3 ⊑ 1, 3 ⊑ 2, 1 ⊑ 0, 2 ⊑ 0
        let p = Poset::from_edges(
            vec![
                (nid(3), nid(1)),
                (nid(3), nid(2)),
                (nid(1), nid(0)),
                (nid(2), nid(0)),
            ],
            std::iter::empty(),
        )
        .unwrap();
        assert!(!p.is_tree());
        assert_eq!(p.roots().len(), 1);
        assert_eq!(p.max_depth(), 2);
    }

    #[test]
    fn cycle_is_rejected() {
        let err = Poset::from_edges(
            vec![(nid(0), nid(1)), (nid(1), nid(2)), (nid(2), nid(0))],
            std::iter::empty(),
        )
        .unwrap_err();
        assert!(matches!(err, HierarchyError::NotAcyclic { .. }));
    }

    #[test]
    fn self_loop_is_a_cycle() {
        let err = Poset::from_edges(vec![(nid(0), nid(0))], std::iter::empty()).unwrap_err();
        assert!(matches!(err, HierarchyError::NotAcyclic { .. }));
    }

    #[test]
    fn topo_up_puts_children_before_parents() {
        let p = Poset::from_edges(vec![(nid(2), nid(1)), (nid(1), nid(0))], std::iter::empty())
            .unwrap();
        let pos: HashMap<u32, usize> = p
            .topo_up()
            .iter()
            .enumerate()
            .map(|(i, &v)| (v, i))
            .collect();
        let (a, b, c) = (
            p.idx(nid(0)).unwrap(),
            p.idx(nid(1)).unwrap(),
            p.idx(nid(2)).unwrap(),
        );
        assert!(pos[&c] < pos[&b]);
        assert!(pos[&b] < pos[&a]);
        // and topo_down is the exact reverse
        assert_eq!(p.topo_down(), vec![a, b, c]);
    }

    #[test]
    fn forest_with_several_roots() {
        let p = Poset::from_edges(vec![(nid(1), nid(0)), (nid(3), nid(2))], std::iter::empty())
            .unwrap();
        assert!(p.is_tree());
        assert_eq!(p.roots().len(), 2);
    }
}
